services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - docker-service

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    ports:
      - "5004:80"
    networks:
      - docker-service
    depends_on:
      - mariadb

  app1:
    build:
      context: .
      dockerfile: Dockerfile.yml
    container_name: app1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/ssDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
    ports:
      - "8080:8080"
    networks:
      - docker-service

  app2:
    build:
      context: .
      dockerfile: Dockerfile.yml
    container_name: app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/ssDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
    ports:
      - "8081:8080"
    networks:
      - docker-service

  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx.yml
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - docker-service

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local